version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  nodejs:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: dockerfile
    container_name: nodejs
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true # keep open the terminal
    tty: true # keep open the terminal

volumes:
  mongodb:
